### PR TITLE
Add some logging utilities to capture whisper.cpp output

### PR DESCRIPTION
**Pull request by tazz4843**

### CODE REVIEW

**Comment by thewh1teagle** [comment]
The module is whisper_sys_log is private not sure how should I use it. Tried to install your branch with the features enabled and it didn't worked.

**Comment by thewh1teagle** [comment]
I cloned your repo, make the modules public but still it doesn't hide it 

image

**Comment by tazz4843** [comment]
To be clear, you did call at least one of `install_whisper_log_trampoline` or `install_whisper_tracing_trampoline`?

**Comment by thewh1teagle** [comment]
Yes

**Comment by tazz4843** [comment]
Gonna go ahead and merge, hopefully it's resolved with some fixes from other PRs. If not, let me know and I'll go ahead and dig into it.

**Pull request merged**
