### PR TITLE
Add CUDA and OpenCL support

### PR DESCRIPTION
**Pull request by tazz4843**
I may have broken other things, however the following are known to work (only on Linux, I have no Windows to test on)
* CUDA on RTX 3060
* OpenCL on AMD Ryzen 7 6800U iGPU
* normal CPU-only transcription on Intel Core i5-8600K and AMD Ryzen 7 6800U with acceleration

PR status: waiting on upstream whisper.cpp release, that way we aren't using an unstable version.

### CODE REVIEW

**Comment by tazz4843** [comment]
Some people to run macOS tests would be appreciated, as I worry I broke some things on there with this.

**Comment by randomairborne** [comment]
I can do macOS tests. Windows tests might need someone else

**Comment by tazz4843** [comment]
Windows shouldn't have broken at all, only `coreml` would likely have been broken.

**Comment by randomairborne** [comment]
```
whisper_init_state: loading Core ML model from 'sys/whisper.cpp/models/ggml-base.en-encoder.mlmodelc'
whisper_init_state: first run on a device may take a while ...
whisper_init_state: failed to load Core ML model from 'sys/whisper.cpp/models/ggml-base.en-encoder.mlmodelc'
thread 'main' panicked at 'failed to create key: InitError', examples/audio_transcription.rs:15:40
```
I believe this is a coreML error, so if anyone is willing to shed some light that would be appreciated

**Comment by tazz4843** [comment]
whisper.cpp v1.4.2 has been released. I'll update master and then merge this PR in, and probably do another release.

**Comment by tazz4843** [comment]
whisper-rs v0.8.0 published.

**Pull request merged**
