### PR TITLE
Add a feature flag for Metal acceleration support

### PR DESCRIPTION
**Pull request by tazz4843**
Should hopefully fix errors along the lines of the following on macOS:

```
 Undefined symbols for architecture x86_64:
            "_MTLCopyAllDevices", referenced from:
                _ggml_metal_init in libwhisper_rs_sys-3c0021a7bf9aa3b1.rlib(ggml-metal.m.o)
            "_MTLCreateSystemDefaultDevice", referenced from:
                _ggml_metal_init in libwhisper_rs_sys-3c0021a7bf9aa3b1.rlib(ggml-metal.m.o)
            "_OBJC_CLASS_$_MTLComputePassDescriptor", referenced from:
                objc-class-ref in libwhisper_rs_sys-3c0021a7bf9aa3b1.rlib(ggml-metal.m.o)
          ld: symbol(s) not found for architecture x86_64
          clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
```
ggml_metal_init: allocating
ggml_metal_init: found device: AMD Radeon Pro 5500M
ggml_metal_init: found device: Intel(R) UHD Graphics 630
ggml_metal_init: picking default device: AMD Radeon Pro 5500M
ggml_metal_init: loading '(null)'
ggml_metal_init: error: Error Domain=NSCocoaErrorDomain Code=258 "The file name is invalid."
```

cc @cenzovit

### CODE REVIEW

**Comment by codesoda** [comment]
Pretty excited to see this in action

**Comment by jungsu0717** [comment]
Is the issue resolved?
I'm developing a macOS app based on your project.

`Undefined symbols for architecture arm64:
            "_MTLCopyAllDevices", referenced from:
                _ggml_metal_init in libwhisper_rs_sys-0c9543eb5bd16852.rlib(ggml-metal.m.o)
            "_MTLCreateSystemDefaultDevice", referenced from:
                _ggml_metal_init in libwhisper_rs_sys-0c9543eb5bd16852.rlib(ggml-metal.m.o)
            "_OBJC_CLASS_$_MTLComputePassDescriptor", referenced from:
                objc-class-ref in libwhisper_rs_sys-0c9543eb5bd16852.rlib(ggml-metal.m.o)
            "_OBJC_CLASS_$_NSBundle", referenced from:
                objc-class-ref in libwhisper_rs_sys-0c9543eb5bd16852.rlib(ggml-metal.m.o)
            "_OBJC_CLASS_$_NSString", referenced from:
                objc-class-ref in libwhisper_rs_sys-0c9543eb5bd16852.rlib(ggml-metal.m.o)
          ld: symbol(s) not found for architecture arm64
          clang: error: linker command failed with exit code 1 (use -v to see invocation)`

How can I fix?

**Comment by jungti1234** [comment]
> No one's tested this besides me, with an Apple unsupported macOS system, so I'm hesitant to merge yet.

I tested it on my M2 macbook pro, build succeed but there was no change in GPU usage when I use whisper, so I think can't sure it works or not... 😢 I'm will keep try to find a way for success of metal acceleration support.

**Comment by garyhai** [comment]
I test it on M1 Mac mini, Intel iMac and Intel Macbook. All build succeed and examples works. It seems GPU is being utilized as well on M1 Mac.

**Comment by tazz4843** [comment]
Given that I didn't change anything fundamentally with those merge conflicts, I'm going to go ahead and merge. If it breaks again, let me know.

**Comment by jungsu0717** [comment]
I just tried it and the build works fine, but there is no log that metal was used. 

What am I missing?

```
whisper_init_from_file_no_state: loading model from '/ggml-small.bin'
whisper_model_load: loading model
whisper_model_load: n_vocab       = 51865
whisper_model_load: n_audio_ctx   = 1500
whisper_model_load: n_audio_state = 768
whisper_model_load: n_audio_head  = 12
whisper_model_load: n_audio_layer = 12
whisper_model_load: n_text_ctx    = 448
whisper_model_load: n_text_state  = 768
whisper_model_load: n_text_head   = 12
whisper_model_load: n_text_layer  = 12
whisper_model_load: n_mels        = 80
whisper_model_load: ftype         = 1
whisper_model_load: qntvr         = 0
whisper_model_load: type          = 3
whisper_model_load: adding 1608 extra tokens
whisper_model_load: model ctx     =  464.68 MB
whisper_model_load: model size    =  464.44 MB
whisper_init_state: kv self size  =   15.75 MB
whisper_init_state: kv cross size =   52.73 MB
whisper_init_state: compute buffer (conv)   =   19.96 MB
whisper_init_state: compute buffer (encode) =  122.04 MB
whisper_init_state: compute buffer (cross)  =    5.86 MB
whisper_init_state: compute buffer (decode) =   36.17 MB
whisper_full_with_state: auto-detected language: ko (p = 0.991928)
```

**Comment by tazz4843** [comment]
That I have no clue about. It could be anything. As far as I can tell, we are linking with the required libraries now, so it should work fine. Like I said, I'm on an Apple-unsupported setup (macOS 14 on a 2012 MBP with legacy Metal support) so I doubt most of what I try will apply to others.

**Comment by codesoda** [comment]
@jungsu0717 did you specify to use the "metal" feature, ie

```
[dependencies]
whisper-rs = { git = "https://github.com/tazz4843/whisper-rs", branch = "master", features = ["metal"] }
```

**Comment by jungsu0717** [comment]
Successfully used metal! thanks @codesoda 👍

But something else happened. 😭

```
whisper_init_from_file_no_state: loading model from 'ggml-small.bin'
whisper_model_load: loading model
whisper_model_load: n_vocab       = 51865
whisper_model_load: n_audio_ctx   = 1500
whisper_model_load: n_audio_state = 768
whisper_model_load: n_audio_head  = 12
whisper_model_load: n_audio_layer = 12
whisper_model_load: n_text_ctx    = 448
whisper_model_load: n_text_state  = 768
whisper_model_load: n_text_head   = 12
whisper_model_load: n_text_layer  = 12
whisper_model_load: n_mels        = 80
whisper_model_load: ftype         = 1
whisper_model_load: qntvr         = 0
whisper_model_load: type          = 3
whisper_model_load: adding 1608 extra tokens
whisper_model_load: model ctx     =  464.68 MB
whisper_model_load: model size    =  464.44 MB
whisper_init_state: kv self size  =   15.75 MB
whisper_init_state: kv cross size =   52.73 MB
whisper_init_state: compute buffer (conv)   =   19.96 MB
whisper_init_state: compute buffer (encode) =  122.04 MB
whisper_init_state: compute buffer (cross)  =    5.86 MB
whisper_init_state: compute buffer (decode) =   36.17 MB
ggml_metal_init: allocating
ggml_metal_init: found device: Apple M1 Pro
ggml_metal_init: picking default device: Apple M1 Pro
ggml_metal_init: loading '(null)'
ggml_metal_init: error: Error Domain=NSCocoaErrorDomain Code=258 "The file name is invalid."
whisper_init_state: ggml_metal_init() failed
```

**Comment by jungsu0717** [comment]
I'm creating a MacOS app with flutter (m1 silicon)
After looking at several issues, I realized that ggml-metal.metal is not recognized in the path.

After forking your project, I set the master branch to submodule from https://github.com/ggerganov/whisper.cpp.

Put the ggml-metal.metal in Xcode > Build Phases > Copy Bundle Resources and it found the path correctly and worked fine.

I hope this helps those who are using it in the same environment as me.

```
whisper_init_from_file_with_params_no_state: loading model from 'ggml-small.bin'
whisper_model_load: loading model
whisper_model_load: n_vocab       = 51865
whisper_model_load: n_audio_ctx   = 1500
whisper_model_load: n_audio_state = 768
whisper_model_load: n_audio_head  = 12
whisper_model_load: n_audio_layer = 12
whisper_model_load: n_text_ctx    = 448
whisper_model_load: n_text_state  = 768
whisper_model_load: n_text_head   = 12
whisper_model_load: n_text_layer  = 12
whisper_model_load: n_mels        = 80
whisper_model_load: ftype         = 1
whisper_model_load: qntvr         = 0
whisper_model_load: type          = 3 (small)
whisper_model_load: adding 1608 extra tokens
whisper_model_load: n_langs       = 99
whisper_backend_init: using Metal backend
ggml_metal_init: allocating
ggml_metal_init: found device: Apple M1 Pro
ggml_metal_init: picking default device: Apple M1 Pro
ggml_metal_init: loading 'Users/Documents/project/${project_name}/build/macos/Build/Products/Debug/MacOS.app/Contents/Resources/default.metallib'
ggml_metal_init: GPU name:   Apple M1 Pro
ggml_metal_init: GPU family: MTLGPUFamilyApple7 (1007)
ggml_metal_init: hasUnifiedMemory              = true
ggml_metal_init: recommendedMaxWorkingSetSize  = 21845.34 MB
ggml_metal_init: maxTransferRate               = built-in GPU
ggml_metal_add_buffer: allocated 'backend         ' buffer, size =   477.81 MB, (  536.80 / 21845.34)
whisper_model_load:    Metal buffer size =   477.80 MB
whisper_model_load: model size    =  477.62 MB
whisper_backend_init: using Metal backend
ggml_metal_init: allocating
ggml_metal_init: found device: Apple M1 Pro
ggml_metal_init: picking default device: Apple M1 Pro
ggml_metal_init: loading '/Users/yunjeongsu/Documents/project/flutter_project/shadow_flutter/build/macos/Build/Products/Debug/Shadow.app/Contents/Resources/default.metallib'
ggml_metal_init: GPU name:   Apple M1 Pro
ggml_metal_init: GPU family: MTLGPUFamilyApple7 (1007)
ggml_metal_init: hasUnifiedMemory              = true
ggml_metal_init: recommendedMaxWorkingSetSize  = 21845.34 MB
ggml_metal_init: maxTransferRate               = built-in GPU
ggml_metal_add_buffer: allocated 'backend         ' buffer, size =    15.75 MB, (  561.80 / 21845.34)
whisper_init_state: kv self size  =   15.75 MB
ggml_metal_add_buffer: allocated 'backend         ' buffer, size =    52.73 MB, (  614.53 / 21845.34)
whisper_init_state: kv cross size =   52.73 MB
whisper_init_state: loading Core ML model from '/Users/Documents/project/${project_name}/build/macos/Build/Products/Debug/MacOS.app/Contents/Resources/ggml-small-encoder.mlmodelc'
whisper_init_state: first run on a device may take a while ...
whisper_init_state: failed to load Core ML model from '/Users/Documents/project/${project_name}/build/macos/Build/Products/Debug/MacOS.app/Contents/Resources/ggml-small-encoder.mlmodelc'
ggml_metal_add_buffer: allocated 'backend         ' buffer, size =     0.02 MB, (  614.55 / 21845.34)
whisper_init_state: compute buffer (conv)   =   19.23 MB
ggml_metal_add_buffer: allocated 'backend         ' buffer, size =     0.02 MB, (  614.56 / 21845.34)
whisper_init_state: compute buffer (encode) =  122.14 MB
ggml_metal_add_buffer: allocated 'backend         ' buffer, size =     0.02 MB, (  614.58 / 21845.34)
whisper_init_state: compute buffer (cross)  =    5.96 MB
ggml_metal_add_buffer: allocated 'backend         ' buffer, size =     0.02 MB, (  614.59 / 21845.34)
whisper_init_state: compute buffer (decode) =   36.27 MB
ggml_metal_add_buffer: allocated 'backend         ' buffer, size =    17.67 MB, (  632.27 / 21845.34)
ggml_metal_add_buffer: allocated 'backend         ' buffer, size =   120.58 MB, (  752.84 / 21845.34)
ggml_metal_add_buffer: allocated 'backend         ' buffer, size =     4.41 MB, (  757.25 / 21845.34)
ggml_metal_add_buffer: allocated 'backend         ' buffer, size =    34.70 MB, (  791.95 / 21845.34)
whisper_full_with_state: auto-detected language: ko (p = 0.980018)
took 8860  ms
```

**Pull request merged**
