### PR TITLE
Feat/vulkan

### PR DESCRIPTION
**Pull request by thewh1teagle**
Add support for vulkan backend in latest whisper.cpp.

Depends on https://github.com/tazz4843/whisper-rs/pull/169
Improve version of https://github.com/tazz4843/whisper-rs/pull/168

---

~Also changed whisper.cpp commit to a bit older commit since latest whisper.cpp is broken with vulkan.~

---

Tested on Windows 11. It works fast.

### CODE REVIEW

**Comment by tazz4843** [comment]
Going to make one final release with OpenCL and then another major release with Vulkan, as I found a 80% performance loss in my testing when I tried Vulkan.

**Comment by thewh1teagle** [comment]
> as I found a 80% performance loss in my testing when I tried Vulkan

What specific performance do you mean? the speed or the quality? (Because there's some issues I heard about the quality)
If it's about speed, which OS and what GPU you have?

**Comment by tazz4843** [comment]
Speed, Linux with an Arc A770

**Comment by thewh1teagle** [comment]
> Speed, Arch Linux with an Arc A770

If it's that drastic like 80% slower maybe the logs suggest that whisper fallback to CPU?

**Comment by tazz4843** [comment]
The logs do show whisper running on Vulkan. It's not a major hit to my use case to stay on an old version of whisper forever so I'm likely just going to do that.

```
ggml_vulkan: Found 1 Vulkan devices:
Vulkan0: Intel(R) Arc(tm) A770 Graphics (DG2) (Intel open-source Mesa driver) | uma: 0 | fp16: 1 | warp size: 32
whisper_model_load: Intel(R) Arc(tm) A770 Graphics (DG2) total size =  1176.00 MB
whisper_model_load: model size    = 1176.00 MB
whisper_backend_init_gpu: using Vulkan backend
```

**Pull request merged**
