### PR TITLE
Update to whisper.cpp v1.3.0.

### PR DESCRIPTION
**Pull request by tazz4843**
This PR includes major breaking changes! Check out the CHANGELOG.md file for more information on the changes, and provide feedback after merge here as well.

### CODE REVIEW

**Comment by tazz4843** [comment]
Closes #28 and #29

**Comment by tazz4843** [comment]
Hmm this PR seems to have triggered some issues on my system (Arch Linux, kernel `6.2.11-arch1-1`)

```
  --- stderr
  CMake Error: File /home/zero/data/CLionProjects/whisper-rs/target/package/whisper-rs-sys-0.4.0/whisper.cpp/bindings/javascript/package-tmpl.json does not exist.
  CMake Error at CMakeLists.txt:23 (configure_file):
    configure_file Problem configuring file


  CMake Error at CMakeLists.txt:298 (add_subdirectory):
    add_subdirectory given source "bindings" which is not an existing
    directory.


  thread 'main' panicked at 'Failed to generate build script', build.rs:77:9
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by tazz4843** [comment]
Ah I believe this is the exclude directive in the Cargo.toml excluding the bindings. I'll see how little I can get away with, as I don't want to bloat the size.

**Comment by delta62** [comment]
I have problems using this version as it looks like `create_state()` isn't publicly visible (maybe #41?)

**Comment by tazz4843** [comment]
Oops, I thought I published a new version at some point. I'll do so in an hour or so. Thanks for pointing it out.

**Comment by tazz4843** [comment]
Forgot to mention this, but I published v0.7.0 last night.

**Pull request merged**
