### PR TITLE
feat: vulkan backend

### PR DESCRIPTION
**Pull request by newfla**
The PR introduces/modifies:

- Update whisper.cpp to the latest master commit (at time of writing a new version has not been released yet)
- Refactor build.rs to reflect deprecation of `WHISPER_XYZ` cmake variables and changes to build artifacts folders
- Minor adjustments to binding.rs and WhisperGrammarElementType repr on Windows
- Introduce vulkan support (tested on linux and windows)

Unfortunately I can't test on macos. I would be very happy if someone could give me some feedback on that platform.

arch-vulkan-test

### CODE REVIEW

**Comment by arizhih** [comment]
@newfla 
Hi, I've also created similar PR #169, I don't want to mix adding new features with updating to the new whisper.cpp cause there are a lot of changes. So I just added support for new project structure and it looks like it works.

As for your PR there is some issues despite all tests are passed. If you look into details - bindings not generated and it uses old, but some structures from public API were changed e.g. `speed_up` was removed from `whisper_full_params`, but it exists in our bindings.

So we can split our efforts and leave one PR with updating to the new whisper.cpp version and another one with adding vulkan support. Or you can add missed parts to your PR, feel free to use my PR as reference.

@tazz4843 Hi, please notice that all tests are passed, but really we have problems. What do you think about to disable implicit use of the bundled bindings at all or at least in CI runs?

**Comment by newfla** [comment]
@arizhih
Hi, I will wait your pr to be merged to rebase this branch on top of your work. 
in the meantime I'm converting this pr to a draft so that it can't be merged by mistake before yours.

**Comment by thewh1teagle** [comment]
@newfla 
Did you managed to build whisper.cpp with vulkan on WIndows?

I tried with whisper.cpp directly but it failed with error.

I used the following commands:

```console
# Install vulkan from https://vulkan.lunarg.com/
git clone https://github.com/ggerganov/whisper.cpp
cd whisper.cpp
$env:VULKAN_SDK = "C:\VulkanSDK\1.3.290.0"
cmake -B build . -DGGML_VULKAN=ON -DGGML_CCACHE=OFF
```

And got this error:

```console
-- Found Vulkan: C:/VulkanSDK/1.3.290.0/Lib/vulkan-1.lib (found version "1.3.290") found components: glslc glslangValidator
-- Vulkan found
CMake Error at ggml/src/CMakeLists.txt:613 (add_subdirectory):
  The source directory

    D:/whisper.cpp/ggml/src/vulkan-shaders

  does not contain a CMakeLists.txt file.
```

**Comment by newfla** [comment]
@thewh1teagle windows msvc is fine with this branch without doing anything special. 
VulkanSDK-1.3.290.0, AMD Adrenalin 24.7.1, R5 7530U
vulkansdk
terminal output
gpu stats

**Comment by arizhih** [comment]
@thewh1teagle I can confirm that with this commit https://github.com/ggerganov/whisper.cpp/commit/fe36c909715e6751277ddb020e7892c7670b61d4 (used in pr) you can build whisper.cpp with Vulkan, unfortunately master is broken right now

**Comment by thewh1teagle** [comment]
Thanks. the specific commit works. Looks like master is broken as you said.
I did a bit of tests. It utilize the GPU by 80% and transcribe. But comparing to OpenCL seems like it's a bit slower.

By the way I couldn't enable openblas when compile

**Comment by newfla** [comment]
> @newfla Hi, my PR was merged some time ago, do you have any plans to continue work on this PR?

Hi, from what I see in #170 @thewh1teagle has already started the merge process.
If you agree I would say to continue with #170

**Comment by tazz4843** [comment]
In that case closing in favor of 170

**Pull request closed without merging**
