### PR TITLE
Link against C++ standard library and macOS Accelerate framework

### PR DESCRIPTION
**Pull request by niklaskorz**
When linking together with other crates that depend on C libraries (in my case, ffmpeg), the linker will fail because of missing symbols from the C++ standard library, and on macOS, missing symbols from the Accelerate framework. This can be fixed by linking against both.

### CODE REVIEW

**Comment by rrohrer** [comment]
This patch also fixes building on macOS on my machine.  Hopefully it's merged soon!

**Comment by solaoi** [comment]
this causes a crash with large model.
cargo:rustc-link-lib=dylib=c++

ifstream::read cannot handle a large file on Mac g++.

you should write below on macOS.
cargo:rustc-flags=-lc++

**Comment by niklaskorz** [comment]
> this causes a crash with large model. cargo:rustc-link-lib=dylib=c++
> 
> ifstream::read cannot handle a large file on Mac g++.
> 
> you should write below on macOS. cargo:rustc-flags=-lc++

Can't reproduce. It even appears that `rustc-link-lib=dylib=c++` does the same as `rustc-flags=-lc++` (see <https://doc.rust-lang.org/cargo/reference/build-scripts.html#cargorustc-link-liblib>):

> The rustc-link-lib instruction tells Cargo to link the given library using the compiler's [-l flag](https://doc.rust-lang.org/rustc/command-line-arguments.html#option-l-link-lib).

**Review by tazz4843 — APPROVED** [review]
Whoops I thought I merged this a long time ago. Sorry about that, lgtm

**Pull request merged**
