### PR TITLE
Update whisper.cpp version to 1.5.4

### LINKED ISSUE #103: Process exits when language detection is enabled
I added `set_language(Some("auto"))` to the full_usage example and ran it(whisper-rs v0.10.0, MBP M1 Max, large-v2 model).

```rust
    let ctx = WhisperContext::new_with_params(
        &whisper_path.to_string_lossy(),
        WhisperContextParameters::default()
    ).expect("failed to open model");
    let mut state = ctx.create_state().expect("failed to create key");
    let mut params = FullParams::new(SamplingStrategy::default());
    params.set_progress_callback_safe(|progress| println!("Progress callback: {}%", progress));

    params.set_language(Some("auto")); // Add

    let st = std::time::Instant::now();
    state
        .full(params, &samples)
        .expect("failed to convert samples");
    let et = std::time::Instant::now();
```

The process terminated with the following message:

```bash
...
whisper_model_load: model size    = 3117.02 MB
whisper_init_state: kv self size  =  220.20 MB
whisper_init_state: kv cross size =  245.76 MB
whisper_init_state: compute buffer (conv)   =   30.92 MB
whisper_init_state: compute buffer (encode) =  212.36 MB
whisper_init_state: compute buffer (cross)  =    9.32 MB
whisper_init_state: compute buffer (decode) =   99.17 MB

Process finished with exit code 139 (interrupted by signal 11:SIGSEGV)
```

When I set `Some("en")` or `Some("ja")`, it works correctly,
but `Some("auto")`, `None`, `set_detect_language(true)` also finished the process.

### PR DESCRIPTION
**Pull request by Andreybest**
Title says it all.

Changed version of whisper-rs-sys to 0.8.1

Works for me in simple environment as before.

Fixes #103

### CODE REVIEW

**Comment by tazz4843** [comment]
Looks like whisper.cpp added a new function in these updates, this should be added: see https://github.com/ggerganov/whisper.cpp/compare/d38af151a1ed5378c5a9ae368e767ed22c8ab141...0b9af32a8b3fa7e2ae5f15a9a08f5b10394993f5#diff-46bc59b448d0e369ff4fbbc995a5c509db6caf1cee3a458f17482fae3086e457R318-R319

**Comment by Andreybest** [comment]
> Looks like whisper.cpp added a new function in these updates, this should be added: see [ggerganov/whisper.cpp@d38af15...0b9af32#diff-46bc59b448d0e369ff4fbbc995a5c509db6caf1cee3a458f17482fae3086e457R318-R319](https://github.com/ggerganov/whisper.cpp/compare/d38af151a1ed5378c5a9ae368e767ed22c8ab141...0b9af32a8b3fa7e2ae5f15a9a08f5b10394993f5#diff-46bc59b448d0e369ff4fbbc995a5c509db6caf1cee3a458f17482fae3086e457R318-R319)

My bad, haven't checked .h file changes. Added this function + bumped version of whisper-rs to 0.10.1
And I supposed that the bindings.rs file is being generated into src/ folder, but it's not.
So I've copied it from build folder. Not sure if it's correct approach, sorry - first time working with bindings.

**Comment by tazz4843** [comment]
If possible, can you run bindgen on a Linux system to minimize the change here? If not, no worries, just remove the bindings and I'll do so myself after merge.

**Comment by Andreybest** [comment]
> If possible, can you run bindgen on a Linux system to minimize the change here? If not, no worries, just remove the bindings and I'll do so myself after merge.

Done. Thx.

**Review by tazz4843 — APPROVED** [review]

**Comment by tazz4843** [comment]
Thanks :)

**Pull request merged**
