### PR TITLE
feat: Add support for new whisper.cpp project structure

### PR DESCRIPTION
**Pull request by arizhih**
Add support for new whisper.cpp project structure
Remove opencl feature, removed in whisper.cpp
Add openmp feature and enable by default as in whisper.cpp
Update bindings

### CODE REVIEW

**Comment by arizhih** [comment]
Hi, as I understand they removed it in favor of Vulkan, @newfla already did pr #168

**Comment by tazz4843** [comment]
New major release of whisper-rs will depend on #168 then if OpenCL is gone

**Comment by thewh1teagle** [comment]
Since this update it works 2 times slower on macOS even when coreml and metal features enabled. Any idea why? maybe it doesn't enable it?

**Comment by arizhih** [comment]
@thewh1teagle 
Hi, what about windows/linux on GPU/CPU? Maybe they changed default values for parameters? Do you have any logs?

Maybe it'll be better to create separate issue to continue?

**Comment by thewh1teagle** [comment]
> Hi, what about windows/linux on GPU/CPU?

On Linux / Windows it of course works much faster with Vulkan. the problem is with macOS arm.
Created https://github.com/tazz4843/whisper-rs/issues/176

**Pull request merged**
